# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2b58a7569e58cf277485359c7899f1eb35dcea737d2dde1cf62b166da3b99dcb205e79c2fdb415add69240b2e7f6e33b725c0f5920bed8331c4980ca5c219fb

test:
  secret_key_base: 84c9320feb9b68041b6ae38eec53cb42c26f1d8cea7b0f7680288ffa47d1a124990337739bf1b98999752a363d9c23484efcce91dfd32d64068f7826808f2313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
